name: Publish packages

on:
  push:
    tags:
    - 'v*'

jobs:
  assets:
    name: Release packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        if: matrix.os == 'macos-latest'
        with:
          python-version: 3.6

      # Lower version of glibc is always compatible with greater version
      # So the binary will we runnable on probably all linux stable/LTS distros
      # https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible
      # So I use a custom python image with pyinstaller on centos7 (glibc 2.17)
      - name: Build package for GNU/Linux
        if: matrix.os == 'ubuntu-latest'
        uses: ahmet2mir/docker-python@master
        with:
          make_args: init_pip test build binary-linux binary-tests archive-linux package-rpm package-deb

      - name: Build package for OSX
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-tar
          brew install coreutils
          gem install --user --no-document fpm
          make init_pip test build binary-macos binary-tests archive-macos package-brew

      - name: Upload Release Asset
        uses: ahmet2mir/softprops-action-gh-release@v1
        with:
          files: |
            ./artifacts/archives/*.tar.gz
            ./artifacts/rpm/*.rpm
            ./artifacts/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution to PyPI
        uses: ahmet2mir/pypa-gh-action-pypi-publish@master
        if: matrix.os == 'ubuntu-latest'
        with:
          password: ${{ secrets.GH_ACTIONS_WILD }}
